"""<5th set of models>

Revision ID: 39c5c4d737b6
Revises: 0b5c3858b16c
Create Date: 2023-10-25 22:26:33.622576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c5c4d737b6'
down_revision = '0b5c3858b16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profession')

    # ### end Alembic commands ###
